package co.edu.udea.entity;
// Generated 4/11/2016 10:52:04 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 *Productos generated by hbm2java
 */
@Entity
@Table(name="productos"
    ,catalog="udeacommerce"
)
public class Producto  implements java.io.Serializable {


     private int id;
     private String nombre;
     private Double precio;
     private String imagen;

    public Producto() {
    }

	
    public Producto(int id) {
        this.id = id;
    }
    public Producto(int id, String nombre, Double precio, String imagen) {
       this.id = id;
       this.nombre = nombre;
       this.precio = precio;
       this.imagen = imagen;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="nombre", length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="precio", precision=22, scale=0)
    public Double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Double precio) {
        this.precio = precio;
    }

    
    @Column(name="imagen", length=50)
    public String getImagen() {
        return this.imagen;
    }
    
    public void setImagen(String imagen) {
        this.imagen = imagen;
    }




}


